version: "{build}"

environment:
  matrix:
    - RUBY_VERSION: 233
    - RUBY_VERSION: 226
    - RUBY_VERSION: 219
    - RUBY_VERSION: 200
    - RUBY_VERSION: 193

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - gem install nokogiri -v '1.7.1' --no-ri --no-rdoc
  - bundle install

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake
