version: "{build}"

environment:
  matrix:
    - RUBY_VERSION: 23
    - RUBY_VERSION: 22

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - ruby -v
  - gem -v
  - bundle -v
  - bundle install

build: off

test_script:
  - bundle exec rake
